![imagen](./img/ejercicios.png)

## Ejercicio 1
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

## Ejercicio 2
Extrae todos los impares de `my_array`:
1. Mediante bucle for
2. Mediante list comprehension
3. Mediante máscaras

## Ejercicio 3
En un nuevo array, sustituye todos los impares de `my_array` por -1.
1. Mediante máscaras
2. Mediante un `where`

## Ejercicio 4
Imprime por pantalla la secuencia [8 7] del array `my_array`

## Ejercicio 5
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

## Ejercicio 6
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

## Ejercicio 7
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

## Ejercicio 8
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

## Ejercicio 9
Obtén las siguientes secuencias:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```
```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

## Ejercicio 10
Lee la imagen "numpy.png"

## Ejercicio 11
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

## Ejercicio 12
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

## Ejercicio 13

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

## Ejercicio 14

Crea un array de 10 0s. ¿Cuánto ocupa en memoria ocupa en bytes y en bits?


## Ejercicio 15
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. Encapsúlalo en una función, con un argumento de entrada de un vector.

## Ejercicio 16
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo, sumatorio, media y mediana.

## Ejercicio 17
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```